;;; org-notely-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-notely.el

(autoload 'org-notely "org-notely" "\
Insert a new subheading at PARENT-MARKER and show it in an indirect buffer.
Returns the indirect buffer.  In the indirect buffer, \"RET\" is
bound to a function which renames the buffer to the first
heading's name when point is on a heading.  When BURY, the parent
buffer is buried.

Interactively, PARENT-MARKER is set according to
`org-notely-file' and `org-notely-outline-path', which see.

(fn &optional PARENT-MARKER &key (BURY t))" t)
(autoload 'org-notely-here "org-notely" "\
Make a new heading at point and show it in an indirect buffer." t)
(register-definition-prefixes "org-notely" '("org-notely-"))

;;; End of scraped data

(provide 'org-notely-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-notely-autoloads.el ends here
