;;; show-font-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from show-font.el

(autoload 'show-font-handler "show-font" "\
Handle the given I/O `file-name-handler-alist' OPERATION with ARGS.
Determine how to render the font file contents in a buffer.

(fn OPERATION &rest ARGS)")
(autoload 'show-font-select-preview "show-font" "\
Prepare a preview for font FAMILY.
When called interactively, prompt for FAMILY.  When called from Lisp,
FAMILY is a string that satisfies `show-font-installed-p'.

(fn FAMILY)" t)
(autoload 'show-font-tabulated "show-font" "\
Produce a tabulated view of installed fonts with `show-font-pangram' preview.
With optional REGEXP as a prefix argument, prompt for a string or
regular expression to list only fonts matching the given input.
Otherwise, list all installed fonts.

(fn &optional REGEXP)" t)
(autoload 'show-font-mode "show-font" "\
Major mode to preview a font file's character set.

(fn)" t)
(add-to-list 'file-name-handler-alist (cons "\\.\\(ttf\\|otf\\)\\'" #'show-font-handler))
(add-to-list 'auto-mode-alist (cons "\\.\\(ttf\\|otf\\)\\'" 'show-font-mode))
(register-definition-prefixes "show-font" '("show-font-"))

;;; End of scraped data

(provide 'show-font-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; show-font-autoloads.el ends here
