;;; mosey-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mosey.el

(autoload 'mosey "mosey" "\
Move the point according to the list of MOVE-FUNCS.

Each function in MOVE-FUNCS should move the point to a
significant position, usually on the current line, but
potentially across lines.

If BACKWARD is set, move backwards.

If BOUNCE is set, bounce back to the next-to-last position when
the last one is hit.

If CYCLE is set, cycle around when the beginning/end of line is
hit.  Otherwise, stop at beginning/end of line.

(fn MOVE-FUNCS &key BACKWARD BOUNCE CYCLE)" t)
(autoload 'defmosey "mosey" "\
Define `mosey-forward' and `mosey-backward' functions, with `-bounce' and `-cycle' variants.

MOVE-FUNCS is a list of functions that should should move the
point to a significant position, usually on the current line, but
potentially across lines.

PREFIX, if set, appends a prefix to the function names, like
`mosey-prefix-forward', useful for defining different sets of
moseys for different modes.

(fn MOVE-FUNCS &key PREFIX)" nil t)
(defmosey '(beginning-of-line back-to-indentation mosey-goto-end-of-code mosey-goto-beginning-of-comment-text end-of-line))
(register-definition-prefixes "mosey" '("mosey-goto-"))

;;; End of scraped data

(provide 'mosey-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mosey-autoloads.el ends here
