;;; org-make-toc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-make-toc.el

(autoload 'org-make-toc "org-make-toc" "\
Make or update table of contents in current buffer." t)
(autoload 'org-make-toc-at-point "org-make-toc" "\
Make or update table of contents at current entry." t)
(autoload 'org-make-toc-insert "org-make-toc" "\
Insert \":CONTENTS:\" drawer at point." t)
(autoload 'org-make-toc-set "org-make-toc" "\
Set TOC PROPERTIES of entry at point.

(fn PROPERTIES)" t)
(autoload 'org-make-toc-mode "org-make-toc" "\
Add `org-make-toc' to the `before-save-hook' in the current Org buffer.
With prefix argument ARG, turn on if positive, otherwise off.

(fn &optional ARG)" t)
(register-definition-prefixes "org-make-toc" '("org-make-toc-"))

;;; End of scraped data

(provide 'org-make-toc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-make-toc-autoloads.el ends here
