;;; org-bookmark-heading-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-bookmark-heading.el

(autoload 'org-bookmark-heading-make-record "org-bookmark-heading" "\
Return bookmark record for current heading.
Sets ID property for heading if necessary.")
(autoload 'org-bookmark-heading-jump "org-bookmark-heading" "\
Jump to `org-bookmark-heading' BOOKMARK.
BOOKMARK record should have fields `map', `outline-path', and
`id', (and, for compatibility, `front-context-string' is also
supported, in which case it should be an entry ID).

(fn BOOKMARK)")
(define-obsolete-function-alias 'org-bookmark-jump 'org-bookmark-heading-jump "1.2")
(register-definition-prefixes "org-bookmark-heading" '("org-bookmark-heading-"))

;;; End of scraped data

(provide 'org-bookmark-heading-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-bookmark-heading-autoloads.el ends here
