;;; inspector-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from inspector.el

(autoload 'inspector-inspect-expression "inspector" "\
Evaluate EXP and inspect its result.

(fn EXP)" t)
(autoload 'inspector-inspect "inspector" "\
Top-level function for inspecting OBJECTs.
When PRESERVE-HISTORY is T, inspector history is not cleared.

(fn OBJECT &optional PRESERVE-HISTORY)")
(autoload 'inspector-inspect-last-sexp "inspector" "\
Evaluate sexp before point and inspect the result." t)
(autoload 'inspector-inspect-defun "inspector" "\
Evaluate the top s-exp - simmilar the effect
 of M-x or eval-defun and inspect the result" t)
(autoload 'inspector-inspect-region "inspector" "\
Evaluate the region from START TO END and inspect the result.

(fn START END)" t)
(autoload 'inspector-pprint-inspected-object "inspector" "\
Pretty print the object being inspected." t)
(autoload 'inspector-inspect-debugger-locals "inspector" "\
Inspect local variables of the frame at point in debugger backtrace." t)
(autoload 'inspector-inspect-debugger-local "inspector" "\
Inspect local variable named VARNAME of frame at point in debugger backtrace.

(fn VARNAME)" t)
(autoload 'inspector-inspect-debugger-return-value "inspector" "\
Inspect the current return value in the debugger." t)
(autoload 'inspector-inspect-stack-frame "inspector" "\
Inspect current frame and locals in debugger backtrace." t)
(autoload 'inspector-inspect-in-stack-frame "inspector" "\
Inspect an expression, in an environment like that outside the debugger.
The environment used is the one when entering the activation frame at point.

(fn EXP)" t)
(autoload 'inspector-inspect-edebug-expression "inspector" "\
Evaluate EXPR in `edebug-mode', and inspect the result.

(fn EXPR)" t)
(register-definition-prefixes "inspector" '("inspector-"))


;;; Generated autoloads from inspector-tests.el

(register-definition-prefixes "inspector-tests" '("inspector-tests-"))

;;; End of scraped data

(provide 'inspector-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; inspector-autoloads.el ends here
