;;; fish-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from fish-mode.el

(autoload 'fish_indent-before-save "fish-mode" nil t)
(autoload 'fish-mode "fish-mode" "\
Major mode for editing fish shell files.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.fish\\'" . fish-mode))
(add-to-list 'auto-mode-alist '("/fish_funced\\..*\\'" . fish-mode))
(add-to-list 'interpreter-mode-alist '("fish" . fish-mode))
(register-definition-prefixes "fish-mode" '("fish"))

;;; End of scraped data

(provide 'fish-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; fish-mode-autoloads.el ends here
