;;; highlight-function-calls-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from highlight-function-calls.el

(autoload 'highlight-function-calls-mode "highlight-function-calls" "\
Highlight function calls.

Toggle highlighting of function calls on or off.

With a prefix argument ARG, enable if ARG is positive, and
disable it otherwise.  If called from Lisp, enable the mode if
ARG is omitted or nil, and toggle it if ARG is `toggle'.

(fn &optional ARG)" t)
(register-definition-prefixes "highlight-function-calls" '("highlight-function-calls-"))

;;; End of scraped data

(provide 'highlight-function-calls-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; highlight-function-calls-autoloads.el ends here
