;;; ef-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ef-arbutus-theme.el

(register-definition-prefixes "ef-arbutus-theme" '("ef-arbutus-palette"))


;;; Generated autoloads from ef-autumn-theme.el

(register-definition-prefixes "ef-autumn-theme" '("ef-autumn-palette"))


;;; Generated autoloads from ef-bio-theme.el

(register-definition-prefixes "ef-bio-theme" '("ef-bio-palette"))


;;; Generated autoloads from ef-cherie-theme.el

(register-definition-prefixes "ef-cherie-theme" '("ef-cherie-palette"))


;;; Generated autoloads from ef-cyprus-theme.el

(register-definition-prefixes "ef-cyprus-theme" '("ef-cyprus-palette"))


;;; Generated autoloads from ef-dark-theme.el

(register-definition-prefixes "ef-dark-theme" '("ef-dark-palette"))


;;; Generated autoloads from ef-day-theme.el

(register-definition-prefixes "ef-day-theme" '("ef-day-palette"))


;;; Generated autoloads from ef-deuteranopia-dark-theme.el

(register-definition-prefixes "ef-deuteranopia-dark-theme" '("ef-deuteranopia-dark-palette"))


;;; Generated autoloads from ef-deuteranopia-light-theme.el

(register-definition-prefixes "ef-deuteranopia-light-theme" '("ef-deuteranopia-light-palette"))


;;; Generated autoloads from ef-dream-theme.el

(register-definition-prefixes "ef-dream-theme" '("ef-dream-palette"))


;;; Generated autoloads from ef-duo-dark-theme.el

(register-definition-prefixes "ef-duo-dark-theme" '("ef-duo-dark-palette"))


;;; Generated autoloads from ef-duo-light-theme.el

(register-definition-prefixes "ef-duo-light-theme" '("ef-duo-light-palette"))


;;; Generated autoloads from ef-eagle-theme.el

(register-definition-prefixes "ef-eagle-theme" '("ef-eagle-palette"))


;;; Generated autoloads from ef-elea-dark-theme.el

(register-definition-prefixes "ef-elea-dark-theme" '("ef-elea-dark-palette"))


;;; Generated autoloads from ef-elea-light-theme.el

(register-definition-prefixes "ef-elea-light-theme" '("ef-elea-light-palette"))


;;; Generated autoloads from ef-frost-theme.el

(register-definition-prefixes "ef-frost-theme" '("ef-frost-palette"))


;;; Generated autoloads from ef-kassio-theme.el

(register-definition-prefixes "ef-kassio-theme" '("ef-kassio-palette"))


;;; Generated autoloads from ef-light-theme.el

(register-definition-prefixes "ef-light-theme" '("ef-light-palette"))


;;; Generated autoloads from ef-maris-dark-theme.el

(register-definition-prefixes "ef-maris-dark-theme" '("ef-maris-dark-palette"))


;;; Generated autoloads from ef-maris-light-theme.el

(register-definition-prefixes "ef-maris-light-theme" '("ef-maris-light-palette"))


;;; Generated autoloads from ef-melissa-dark-theme.el

(register-definition-prefixes "ef-melissa-dark-theme" '("ef-melissa-dark-palette"))


;;; Generated autoloads from ef-melissa-light-theme.el

(register-definition-prefixes "ef-melissa-light-theme" '("ef-melissa-light-palette"))


;;; Generated autoloads from ef-night-theme.el

(register-definition-prefixes "ef-night-theme" '("ef-night-palette"))


;;; Generated autoloads from ef-owl-theme.el

(register-definition-prefixes "ef-owl-theme" '("ef-owl-palette"))


;;; Generated autoloads from ef-reverie-theme.el

(register-definition-prefixes "ef-reverie-theme" '("ef-reverie-palette"))


;;; Generated autoloads from ef-rosa-theme.el

(register-definition-prefixes "ef-rosa-theme" '("ef-rosa-palette"))


;;; Generated autoloads from ef-spring-theme.el

(register-definition-prefixes "ef-spring-theme" '("ef-spring-palette"))


;;; Generated autoloads from ef-summer-theme.el

(register-definition-prefixes "ef-summer-theme" '("ef-summer-palette"))


;;; Generated autoloads from ef-symbiosis-theme.el

(register-definition-prefixes "ef-symbiosis-theme" '("ef-symbiosis-palette"))


;;; Generated autoloads from ef-themes.el

(defvar ef-themes-take-over-modus-themes-mode nil "\
Non-nil if Ef-Themes-Take-Over-Modus-Themes mode is enabled.
See the `ef-themes-take-over-modus-themes-mode' command
for a description of this minor mode.")
(custom-autoload 'ef-themes-take-over-modus-themes-mode "ef-themes" nil)
(autoload 'ef-themes-take-over-modus-themes-mode "ef-themes" "\
When enabled, all Modus themes commands consider only Ef themes.

Alternatively, use the commands `ef-themes-rotate', `ef-themes-select',
`ef-themes-load-random', `ef-themes-load-random-dark',
`ef-themes-load-random-light', `ef-themes-list-colors',
`ef-themes-list-colors-current'.  They are all designed to only consider
Ef themes.

This is a global minor mode.  If called interactively, toggle the
`Ef-Themes-Take-Over-Modus-Themes mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='ef-themes-take-over-modus-themes-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
 (autoload 'ef-themes-toggle "ef-themes")
 (autoload 'ef-themes-rotate "ef-themes")
 (autoload 'ef-themes-select "ef-themes")
 (autoload 'ef-themes-load-random "ef-themes")
 (autoload 'ef-themes-load-random-dark "ef-themes")
 (autoload 'ef-themes-load-random-light "ef-themes")
 (autoload 'ef-themes-list-colors "ef-themes")
 (autoload 'ef-themes-list-colors-current "ef-themes")
(when load-file-name (let ((dir (file-name-directory load-file-name))) (unless (file-equal-p dir (expand-file-name "themes/" data-directory)) (add-to-list 'custom-theme-load-path dir))))
(register-definition-prefixes "ef-themes" '("ef-themes-"))


;;; Generated autoloads from ef-trio-dark-theme.el

(register-definition-prefixes "ef-trio-dark-theme" '("ef-trio-dark-palette"))


;;; Generated autoloads from ef-trio-light-theme.el

(register-definition-prefixes "ef-trio-light-theme" '("ef-trio-light-palette"))


;;; Generated autoloads from ef-tritanopia-dark-theme.el

(register-definition-prefixes "ef-tritanopia-dark-theme" '("ef-tritanopia-dark-palette"))


;;; Generated autoloads from ef-tritanopia-light-theme.el

(register-definition-prefixes "ef-tritanopia-light-theme" '("ef-tritanopia-light-palette"))


;;; Generated autoloads from ef-winter-theme.el

(register-definition-prefixes "ef-winter-theme" '("ef-winter-palette"))

;;; End of scraped data

(provide 'ef-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ef-themes-autoloads.el ends here
