;;; standard-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from standard-dark-theme.el

(put 'standard-dark 'theme-properties (list :background-mode 'dark :kind 'color-scheme :family 'standard))


;;; Generated autoloads from standard-light-theme.el

(put 'standard-light 'theme-properties (list :background-mode 'light :kind 'color-scheme :family 'standard))


;;; Generated autoloads from standard-themes.el

(autoload 'standard-themes-load-dark "standard-themes" "\
Load `standard-dark' and run `standard-themes-post-load-hook'." t)
(autoload 'standard-themes-load-light "standard-themes" "\
Load `standard-light' and run `standard-themes-post-load-hook'." t)
(autoload 'standard-themes-toggle "standard-themes" "\
Toggle between the `standard-dark' and `standard-light' themes.
Run `standard-themes-post-load-hook' after loading the theme." t)
(autoload 'standard-themes-theme "standard-themes" "\
Bind NAME's color PALETTE around face specs and variables.
Face specifications are passed to `custom-theme-set-faces'.
While variables are handled by `custom-theme-set-variables'.
Those are stored in `standard-themes-faces' and
`standard-themes-custom-variables' respectively.

Optional OVERRIDES are appended to PALETTE, overriding
corresponding entries.

(fn NAME PALETTE &optional OVERRIDES)" nil t)
(function-put 'standard-themes-theme 'lisp-indent-function 0)
(when load-file-name (let ((dir (file-name-directory load-file-name))) (unless (file-equal-p dir (expand-file-name "themes/" data-directory)) (add-to-list 'custom-theme-load-path dir))))
(register-definition-prefixes "standard-themes" '("standard-themes-"))

;;; End of scraped data

(provide 'standard-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; standard-themes-autoloads.el ends here
