;;; deffy-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from deffy.el

(autoload 'deffy "deffy" "\
Show definitions defined in PROJECT or FILES.
Interactively, with PREFIX, show only definitions in current
buffer.

(fn &key (PROJECT (or (project-current) (cons \\='transient default-directory))) (KEYS deffy-taxy-default-keys) (FILES deffy-files) (BUFFER-NAME (format \"*Deffy: %s*\" (if files (string-join (mapcar #\\='file-name-nondirectory files) \", \") (file-name-nondirectory (directory-file-name (project-root project)))))) VISIBILITY-FN DISPLAY-BUFFER-ACTION)" t)
(autoload 'deffy-buffer "deffy" "\
Show an Deffy view for BUFFER.
Interactively, with prefix, display in dedicated side window.

(fn &optional (BUFFER (current-buffer)) &key DISPLAY-BUFFER-ACTION)" t)
(autoload 'deffy-bookmark-handler "deffy" "\
Show Deffy buffer for bookmark RECORD.

(fn RECORD)")
(register-definition-prefixes "deffy" '("deffy-"))

;;; End of scraped data

(provide 'deffy-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; deffy-autoloads.el ends here
