;;; plz-see-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from plz-see.el

(autoload 'plz-see "plz-see" "\
Request METHOD from URL with curl and display the result in a buffer.

If URL starts with \"/\", prepend `plz-see-base-url' to it.

HEADERS may be an alist of extra headers to send with the
request.  Headers listed under `plz-see-base-headers' are
included by default.

BODY may be a string, a buffer, or a list like `(file FILENAME)'
to upload a file from disk.

AS selects the kind of result to pass to the callback function
THEN, or the kind of result to return for synchronous requests.
It may be (note that not all choices provided by the original
`plz' function are supported):

- `buffer' to pass the response buffer (after prettifying it with
  one of the `'plz-see-content-type-alist' entries).

- `response' to pass a `plz-response' structure.

- A function, which is called in the response buffer with it
  narrowed to the response body (suitable for, e.g. `json-read').

THEN is a callback function, whose sole argument is selected
above with AS; if the request fails and no ELSE function is
given (see below), the argument will be a `plz-error' structure
describing the error.  (Note that unlike the original `plz',
synchronous requests are not supported.)

ELSE is an optional callback function called when the request
fails (i.e. if curl fails, or if the HTTP response has a non-2xx
status code).  It is called with one argument, a `plz-error'
structure.

Other possible keyword arguments are BODY-TYPE, DECODE, FINALLY,
CONNECT-TIMEOUT, TIMEOUT and NOQUERY.  They are passed directly
to `plz', which see.

(To silence checkdoc, we mention the internal argument REST.)

(fn METHOD URL &rest REST &key HEADERS THEN ELSE AS &allow-other-keys)" t)
(register-definition-prefixes "plz-see" '("plz-see-"))

;;; End of scraped data

(provide 'plz-see-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; plz-see-autoloads.el ends here
