;;; vundo-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from vundo.el

(autoload 'vundo "vundo" "\
Display visual undo for the current buffer." t)
(register-definition-prefixes "vundo" '("vundo-"))


;;; Generated autoloads from vundo-diff.el

(autoload 'vundo-diff-mark "vundo-diff" "\
Mark NODE for vundo diff.
NODE defaults to the current node.

(fn &optional NODE)" t)
(autoload 'vundo-diff-unmark "vundo-diff" "\
Unmark the node marked for vundo diff." t)
(autoload 'vundo-diff "vundo-diff" "\
Perform diff between marked and current buffer state.
Displays in a separate diff buffer with name based on
the original buffer name." t)
(register-definition-prefixes "vundo-diff" '("vundo-diff-"))

;;; End of scraped data

(provide 'vundo-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vundo-autoloads.el ends here
