;;; defrepeater-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from defrepeater.el

(autoload 'defrepeater "defrepeater" "\
Define NAME-OR-COMMAND as an interactive command which calls COMMAND repeatedly.
COMMAND is called every time the last key of the sequence bound
to NAME is pressed, until another key is pressed. If COMMAND is
given, the repeating command is named NAME-OR-COMMAND and calls
COMMAND; otherwise it is named `NAME-OR-COMMAND-repeat' and calls
NAME-OR-COMMAND.

The newly defined function's symbol is returned, so
e.g. `defrepeater' may be used in a key-binding expression.

(fn NAME-OR-COMMAND &optional COMMAND)" nil t)

;;; End of scraped data

(provide 'defrepeater-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; defrepeater-autoloads.el ends here
